### ISSUE TITLE
Diving is broken after v1.0

### ISSUE THREAD

**Issue by webbongithub** [PeachyPeachSM64/sm64ex-omm#20]
For some reason, diving is broken for me on every version after 1.0. I'm running Linux and using an 8bitdo Pro 2 over USB. When I ground pound and hit B, it does nothing.

**Comment by Isaac0-dev** [comment]
what are you referring to, omm version 1.0?

**Comment by webbongithub** [comment]
> what are you referring to, omm version 1.0?

This post was made before sm64coopdx v1.0, so I mean OMM.

**Comment by Isaac0-dev** [comment]
oh, you're referring to OMM Rebirth, the Lua version. this repo is primarily for ex-omm

**Comment by webbongithub** [comment]
> oh, you're referring to OMM Rebirth, the Lua version. this repo is primarily for ex-omm

This is the GitHub repository listed on the mod page, and there is a branch for the coop version (`coop`). Is this the wrong place?

**Comment by Isaac0-dev** [comment]
its not necessarily the wrong place, you just didn't mention that you were talking about omm rebirth.
I assumed you weren't since this is mainly a repo for ex-omm
