### ISSUE TITLE
Ideas for Updates (I'm actually wondering if you could make it more Odyssey like

### ISSUE THREAD

**Issue by TheBlazingmo** [PeachyPeachSM64/sm64ex-omm#22]
Mario:
- Making the cap jump a single jump instead of double.
- Adding more of a proper vault like in Odyssey.
- Letting Mario Run when Crouch isn't held from a roll.
- Tilting Cappy Sidewards when Up/Down Throwing.
- Add Running Animation (When Mario runs downhill)

Captures:
- Chain Chomp having slingshot physics from Odyssey
- Add Action HUD

Yeah, These are just ideas, but I'd  be very happy if you could make this happen.

**Comment by PeachyPeachSM64** [comment]
cool ideas, but not planned for now
