### ISSUE TITLE
sm64ex Makefile fails with "Makefile:263: *** Failed to extract assets.  Stop."

### ISSUE THREAD

**Issue by ItsKipz** [PeachyPeachSM64/sm64ex-omm#24]
Trying to run the patcher on Windows 11 and after successfully running the builder setup script, attempting to build the game fails with the message in the title. I have tried it on both OpenGL and DirectX, as well as on all available speed settings, and the same error comes up every time. This is a fresh run of the patcher with no added textures or patches. If there are any logs available I wasn't able to find them - with the exception of the "smex.logs.txt" file, which just contains the single line in the title.

**Comment by PeachyPeachSM64** [comment]
fixed in v8.0.0
