### ISSUE TITLE
Win11: error after exec omm_builder.bat

### ISSUE THREAD

**Issue by Gee1111** [PeachyPeachSM64/sm64ex-omm#25]
Python version: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
Checking dependency: `make`... [X] ERROR: Missing dependency. To fix it:
[Windows] Download and run the `OMM Builder Setup Script`.

**Comment by PeachyPeachSM64** [comment]
fixed in v8.0.0
