### ISSUE TITLE
the frame rate is a lie

### ISSUE THREAD

**Issue by JohnnyGuitar42** [PeachyPeachSM64/sm64ex-omm#29]
setting frame rate cap to unlimited doesn't make the frame rate unlimited
game says 60 fps but it feels like 30 
regular render 96 feels way smoother

**Comment by PeachyPeachSM64** [comment]
that's an issue on your side
for unlimited to work you need to turn off vsync
60 fps works properly, use nvidia tools if you don't trust the in-game counter
