### ISSUE TITLE
Does not go to omm builder on linux ubuntu

### ISSUE THREAD

**Issue by 6dyfer** [PeachyPeachSM64/sm64ex-omm#9]
it just pulls up the text editor

**Comment by 6dyfer** [comment]
![Screenshot from 2022-12-05 18-56-11](https://user-images.githubusercontent.com/87343220/205771397-9478ac58-27d8-4d7d-883a-3315989ccca3.png)
![Screenshot from 2022-12-05 18-56-04](https://user-images.githubusercontent.com/87343220/205771399-5c347ec0-7245-425b-85fe-d1d477c4f8fa.png)
![Screenshot from 2022-12-05 18-56-11](https://user-images.githubusercontent.com/87343220/205771410-07eab0a1-d116-4600-9661-e7b6462422a1.png)
![Screenshot from 2022-12-05 18-56-04](https://user-images.githubusercontent.com/87343220/205771413-45653947-fcab-4be7-91d1-ff0b6ebfbca4.png)

**Comment by PeachyPeachSM64** [comment]
You're not supposed to double click on it like a Windows exe, but launching it from the terminal...
Closing it, as it's not a program issue.

**Comment by 6dyfer** [comment]
oh,sorry

**Comment by 6dyfer** [comment]
it does not let me open with terminal
